import Link from "next/link";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex">
        {/* 사이드바 */}
        <nav className="fixed h-screen p-8 text-lg text-white bg-slate-700">
          <ul className="flex flex-col justify-start gap-4 overflow-scroll">
            <li>
              <Link href="/">Home</Link>
            </li>
            <li>
              <Link href="/sphere">Sphere</Link>
            </li>
          </ul>
        </nav>

        {/* 메인 영역 */}
        <main>{children}</main>
      </body>
    </html>
  );
}
